#!/usr/bin/env bash
# things-cli installer
#
#   1. Create/refresh a venv at <repo>/.venv with things.py installed
#      (uses `uv` if present, falls back to stdlib `venv` + `pip`)
#   2. Write a launcher at ~/.local/bin/things that uses that venv
#   3. Symlink SKILL.md into ~/.claude/skills/things/
#
# Idempotent — safe to re-run.

set -euo pipefail

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
venv_dir="$repo_dir/.venv"
bin_dir="$HOME/.local/bin"
skill_dir="$HOME/.claude/skills/things"
launcher="$bin_dir/things"
req_file="$repo_dir/requirements.txt"

# --- 1. venv ---------------------------------------------------------------
if command -v uv >/dev/null 2>&1; then
    echo "[things-cli] using uv"
    [[ -d "$venv_dir" ]] || uv venv "$venv_dir" >/dev/null
    uv pip install --quiet --python "$venv_dir/bin/python" -r "$req_file"
else
    echo "[things-cli] uv not found, using stdlib venv + pip"
    command -v python3 >/dev/null || {
        echo "[things-cli] python3 not found — install Python 3.10+" >&2
        exit 1
    }
    [[ -d "$venv_dir" ]] || python3 -m venv "$venv_dir"
    "$venv_dir/bin/pip" install --quiet --upgrade pip
    "$venv_dir/bin/pip" install --quiet -r "$req_file"
fi
echo "[things-cli] venv ready: $venv_dir"

# --- 2. launcher ----------------------------------------------------------
chmod +x "$repo_dir/bin/things"
mkdir -p "$bin_dir"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# auto-generated by things-cli/install.sh — do not edit by hand
exec "$venv_dir/bin/python" "$repo_dir/bin/things" "\$@"
EOF
chmod +x "$launcher"
echo "[things-cli] launcher: $launcher"

# --- 3. skill -------------------------------------------------------------
mkdir -p "$skill_dir"
ln -sfn "$repo_dir/SKILL.md" "$skill_dir/SKILL.md"
echo "[things-cli] skill:    $skill_dir/SKILL.md"

# --- 4. PATH check --------------------------------------------------------
if ! printf '%s\n' "$PATH" | tr ':' '\n' | grep -qxF "$bin_dir"; then
    echo
    echo "[things-cli] WARNING: $bin_dir is not on \$PATH."
    echo "[things-cli] Add to your shell rc (~/.zshrc or ~/.bashrc):"
    echo
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

echo
echo "Done. Try:  things today"
